# Fichier de configuration Netlify

[build]
  # Dossier des fonctions serverless
  functions = "netlify/functions"

# L'API dyalna
[[redirects]]
  from = "/api/getProducts"
  to = "/.netlify/functions/getProducts"
  status = 200